In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling
from datetime import datetime
sys.path.append('../scripts')
from feature_transform import dates_encoder, merge_path

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
X_train = pd.read_csv('../data/flights_train.csv')
X_test = pd.read_csv('../data/flights_Xtest.csv')

In [3]:
train_processed = pd.get_dummies(merge_path(dates_encoder(X_train)))
test_processed = pd.get_dummies(merge_path(dates_encoder(X_test)))

In [5]:
dates_encoder(X_train).dtypes

from               object
to                 object
avg_weeks         float64
target            float64
std_weeks         float64
year                int64
month               int64
day                 int64
weekday             int64
week               UInt32
number_of_days      int64
dtype: object

In [4]:
train_processed

,avg_weeks,target,std_weeks,year,month,day,weekday,week,number_of_days,path_ATL_BOS,...,path_SFO_ATL,path_SFO_BOS,path_SFO_DEN,path_SFO_DFW,path_SFO_EWR,path_SFO_JFK,path_SFO_LAS,path_SFO_LAX,path_SFO_ORD,path_SFO_SEA
0,12.875000,12.331296,9.812647,2012,6,19,1,25,15510,0,...,0,0,0,0,0,0,0,0,0,0
1,14.285714,10.775182,9.466734,2012,9,10,0,37,15593,0,...,0,0,0,0,0,0,0,0,0,0
2,10.863636,11.083177,9.035883,2012,10,5,4,40,15618,0,...,0,0,0,0,0,0,0,0,0,0
3,11.480000,11.169268,7.990202,2011,10,9,6,40,15256,0,...,0,0,0,0,0,0,0,0,0,0
4,11.450000,11.269364,9.517159,2012,2,21,1,8,15391,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8891,11.045455,9.795363,7.791798,2011,11,24,3,47,15302,0,...,0,0,0,0,0,0,0,0,0,0
8892,11.000000,9.429776,7.937254,2012,9,1,5,35,15584,0,...,0,0,0,0,0,0,0,0,0,0
8893,9.476190,12.029971,6.903760,2012,8,10,4,32,15562,0,...,0,0,0,0,0,0,0,0,0,0
8894,10.250000,9.381645,7.107261,2012,7,3,1,27,15524,0,...,0,0,0,0,0,0,0,0,0,0
8895,6.727273,8.076713,6.388911,2012,2,25,5,8,15395,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
train_processed.to_csv('../data/flights_train_processed.csv')
test_processed.to_csv('../data/flights_Xtest_processed.csv')